### ISSUE TITLE
Verlinkung der E-Mail-Adresse fehlerhaft.

### ISSUE THREAD

**Issue by d4s6** [devmount/devmount#1]
Die Verlinkung der E-Mail-Adresse ist ein Pfad relativ zur angezeigten Seite. Ein `mailto:` sollte helfen:

```diff
- [email](hello@devmount.de)
+ [email](mailto:hello@devmount.de)
```

**Comment by devmount** [comment]
Wow, das ging schnell! Vielen Dank, habs mit 1b1a879f02715a63305c241a41c9f2647e9bbecd gefixt. Da hab ich etwas zu leichtgläubig angenommen, GitHub würde Links auf Mailadressen automatisch erkennen und parsen 😅
